services:
  - type: web
    name: ${{branch}}.desig.io # Service name
    plan: standard # starter, standard, pro, pro plus, pro max, pro ultra
    region: oregon # oregon, frankfurt, ohio, singapore
    branch: ${{branch}}
    env: node
    autoDeploy: true
    disk:
      name: ${{branch}} # Disk name
      mountPath: /var/lib
      sizeGB: 1
    buildCommand: yarn build
    startCommand: yarn start:pro
    domain: ${{branch}}.desig.io # Your domain
    healthCheckPath: /health
