services:
  - type: web
    name: goku.desig.io # Service name
    plan: starter # starter, standard, pro, pro plus, pro max, pro ultra
    region: oregon # oregon, frankfurt, ohio, singapore
    branch: master
    env: node
    autoDeploy: false
    disk:
      name: goku # Disk name
      mountPath: /var/lib
      sizeGB: 1
    buildCommand: yarn build
    startCommand: yarn start:pro
    domain: goku.desig.io # Your domain
    healthCheckPath: /health
